[pytest]
minversion = 7.0
addopts = -q
testpaths = .
python_files = test_*.py *_test.py
python_classes = Test*
python_functions = test_*
norecursedirs = .git .gitignore venv __pycache__
filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
